### ISSUE TITLE
Snapd should be restarted on upgrade

### ISSUE THREAD

**Issue by zyga** [zyga/snapd-arch#1]
See https://github.com/zyga/snapd-gentoo/issues/2 for more details

**Comment by timjp87** [comment]
Hi I created a PR #2 for this. I saw this comment here: 
https://github.com/zyga/snapd-gentoo/issues/2#issuecomment-226142957

But I'm not sure if we really need to restart the socket and timer. snapd needs to restart, because the old version is running in memory, but it shouldn't affect the timer and socket.

**Comment by zyga** [comment]
I think we only need to restart snapd

**Comment by zyga** [comment]
This is no longer happening as all of this is managed by the user
